//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawarmaManager.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Phone { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
    }
}
