//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawarmaManager.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishCompound
    {
        public int Dish { get; set; }
        public int Ingredient { get; set; }
        public decimal Volume { get; set; }
    
        public virtual Dish Dish1 { get; set; }
        public virtual Ingredient Ingredient1 { get; set; }
    }
}
