//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawarmaManager.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCompound
    {
        public int Order { get; set; }
        public int Dish { get; set; }
        public double Price { get; set; }
        public int Count { get; set; }
        public string Status { get; set; }
    
        public virtual Dish Dish1 { get; set; }
        public virtual DishStatus DishStatus { get; set; }
    }
}
